### ISSUE TITLE
No AXP288 PMIC on i2c Bus

### ISSUE THREAD

**Issue by youling257** [Icenowy/axpd#4]
u0_a25@x86:/ $ su
root@x86:/ # sh /storage/emulated/0/battery.sh
i2cget: applet not found
sh: 0: unknown operand
i2cget: applet not found
sh: 0: unknown operand
i2cget: applet not found
sh: 0: unknown operand
i2cget: applet not found
sh: 0: unknown operand
i2cget: applet not found
sh: 0: unknown operand
i2cget: applet not found
sh: 0: unknown operand
i2cget: applet not found
sh: 0: unknown operand
i2cget: applet not found
sh: 0: unknown operand
i2cget: applet not found
sh: 0: unknown operand
i2cget: applet not found
sh: 0: unknown operand
i2cget: applet not found
sh: 0: unknown operand
i2cget: applet not found
sh: 0: unknown operand
No AXP288 PMIC on i2c Bus
113|root@x86:/ # sush /storage/emulated/0/battery.sh
i2cget: applet not found
/storage/emulated/0/battery.sh[16]: [: 0: unexpected operator/operand
i2cget: applet not found
/storage/emulated/0/battery.sh[16]: [: 0: unexpected operator/operand
i2cget: applet not found
/storage/emulated/0/battery.sh[16]: [: 0: unexpected operator/operand
i2cget: applet not found
/storage/emulated/0/battery.sh[16]: [: 0: unexpected operator/operand
i2cget: applet not found
/storage/emulated/0/battery.sh[16]: [: 0: unexpected operator/operand
i2cget: applet not found
/storage/emulated/0/battery.sh[16]: [: 0: unexpected operator/operand
i2cget: applet not found
/storage/emulated/0/battery.sh[16]: [: 0: unexpected operator/operand
i2cget: applet not found
/storage/emulated/0/battery.sh[16]: [: 0: unexpected operator/operand
i2cget: applet not found
/storage/emulated/0/battery.sh[16]: [: 0: unexpected operator/operand
i2cget: applet not found
/storage/emulated/0/battery.sh[16]: [: 0: unexpected operator/operand
i2cget: applet not found
/storage/emulated/0/battery.sh[16]: [: 0: unexpected operator/operand
i2cget: applet not found
/storage/emulated/0/battery.sh[16]: [: 0: unexpected operator/operand
No AXP288 PMIC on i2c Bus
113|root@x86:/ #

**Comment by youling257** [comment]
Kernel version
4.8.0-rc6-android-x86+
root@youling257-ONDA-Tablet #1
Wed Sep 14 15:23:11 CST 2016
Android version
6.0.1
Android security patch level
September 6, 2016
Build number
android_x86-userdebug 6.0.1 MOB31E eng.cwhuang.20160913.030057 test-keys

**Comment by Icenowy** [comment]
It's designed to use on GNU/Linux, not Android.
2016年9月14日 下午5:15于 youling257 notifications@github.com写道：Kernel version
4.8.0-rc6-android-x86+
root@youling257-ONDA-Tablet #1
Wed Sep 14 15:23:11 CST 2016
Android version
6.0.1
Android security patch level
September 6, 2016
Build number
android_x86-userdebug 6.0.1 MOB31E eng.cwhuang.20160913.030057 test-keys

**Comment by youling257** [comment]
do you know Android x86 ？ it used Linux 4.8 kernel

**Comment by Icenowy** [comment]
I don't know...
My device have official Android image, which is technologically ugly but more useful...
2016年9月14日 下午5:18于 youling257 notifications@github.com写道：do you know Android x86 ？ it used Linux 4.8 kernel

**Comment by youling257** [comment]
we must solved z3735f tablet on Android x86 and remix os problem，isn't z3735f on Linux、debian、ubuntu，
now，z3735f Androidx86 problem，wifi、Bluetooth、touchscreen、sound has solved.

**Comment by Icenowy** [comment]
are you an android-x86 developer?
If you are, I may get interested...
But I should backup all my data before wiping my tablet... (It's with a broken stock-Android-only UEFI now)
2016年9月14日 17:22于 youling257 notifications@github.com写道：we must solved z3735f tablet on Android x86 and remix os problem，isn't z3735f on Linux、debian、ubuntu 
now，z3735f Androidx86 problem，wifi、Bluetooth、touchscreen、sound has solved.

**Comment by youling257** [comment]
only Android x86 fans，only know compile Android x86 kernel and modules

**Comment by Icenowy** [comment]
@youling257 The current implementation is too dirty for Android...
Maybe I will rewrite for Android...

**Comment by youling257** [comment]
[battery.zip](https://github.com/Icenowy/axpd/files/471688/battery.zip)
I used this battery.sh many months，some times，it will No AXP288 PMIC on i2c Bus. some times，can read battery，http://pastebin.com/yDAUt2tN ，https://github.com/zhaofengli/iwork8/issues/1

**Comment by youling257** [comment]
yes，some times

root@x86:/ # sush /sdcard/battery.sh
i2cget: read failed: Remote I/O error
/sdcard/battery.sh[16]: [: 0: unexpected operator/operand
i2cget: read failed: Remote I/O error
/sdcard/battery.sh[16]: [: 0: unexpected operator/operand
i2cget: read failed: Remote I/O error
/sdcard/battery.sh[16]: [: 0: unexpected operator/operand
Battery level: 100%
Charging current: 16 (charging)
Current Charge = 256mA
Current DisCharge = 0mA
Battery voltage = 3824mV
Battery level: 100%
Charging current: 17 (charging)
Current Charge = 272mA
Current DisCharge = 0mA
Battery voltage = 3824mV

**Comment by youling257** [comment]
Because Android x86 busybox problem，i install Android newest busybox solved the problem .
